//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("Maloai_ID")]
    public partial class Hanghoa : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Loaihanghoa fMaloai_ID;
        [Association(@"HanghoaReferencesLoaihanghoa")]
        public Loaihanghoa Maloai_ID
        {
            get { return fMaloai_ID; }
            set { SetPropertyValue<Loaihanghoa>(nameof(Maloai_ID), ref fMaloai_ID, value); }
        }
        string fTenhanghoa;
        public string Tenhanghoa
        {
            get { return fTenhanghoa; }
            set { SetPropertyValue<string>(nameof(Tenhanghoa), ref fTenhanghoa, value); }
        }
        string fDVT;
        public string DVT
        {
            get { return fDVT; }
            set { SetPropertyValue<string>(nameof(DVT), ref fDVT, value); }
        }
        decimal fGiaban;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat","### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask","### ### ### ###")]
        public decimal Giaban
        {
            get { return fGiaban; }
            set { SetPropertyValue<decimal>(nameof(Giaban), ref fGiaban, value); }
        }
        [Association(@"HD_HHReferencesHanghoa")]
        public XPCollection<HD_HH> HD_HHs { get { return GetCollection<HD_HH>(nameof(HD_HHs)); } }
        [Association(@"PN_HHReferencesHanghoa")]
        public XPCollection<PN_HH> PN_HHs { get { return GetCollection<PN_HH>(nameof(PN_HHs)); } }
    }

}
