//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("Hoadon_ID")]
    public partial class HD_HH : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Hoadon fHoadon_ID;
        [Association(@"HD_HHReferencesHoadon")]
        public Hoadon Hoadon_ID
        {
            get { return fHoadon_ID; }
            set { SetPropertyValue<Hoadon>(nameof(Hoadon_ID), ref fHoadon_ID, value); }
        }
        Hanghoa fHanghoa_ID;
        [Association(@"HD_HHReferencesHanghoa")]
        public Hanghoa Hanghoa_ID
        {
            get { return fHanghoa_ID; }
            set { SetPropertyValue<Hanghoa>(nameof(Hanghoa_ID), ref fHanghoa_ID, value); }
        }
        double fSoluong;
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat","### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask","### ### ### ###")]
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public string Thanhtien
        {
            get { return (string)(EvaluateAlias(nameof(Thanhtien))); }
        }
    }

}
