//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("HotenKH")]
    public partial class Khachhang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHotenKH;
        public string HotenKH
        {
            get { return fHotenKH; }
            set { SetPropertyValue<string>(nameof(HotenKH), ref fHotenKH, value); }
        }
        string fDiachiKH;
        public string DiachiKH
        {
            get { return fDiachiKH; }
            set { SetPropertyValue<string>(nameof(DiachiKH), ref fDiachiKH, value); }
        }
        string fSDTKH;
        public string SDTKH
        {
            get { return fSDTKH; }
            set { SetPropertyValue<string>(nameof(SDTKH), ref fSDTKH, value); }
        }
        [Association(@"HoadonReferencesKhachhang")]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
