//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("Phanloai_ID")]
    public partial class Loaihanghoa : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fPhanloai;
        public string Phanloai
        {
            get { return fPhanloai; }
            set { SetPropertyValue<string>(nameof(Phanloai), ref fPhanloai, value); }
        }
        [Association(@"HanghoaReferencesLoaihanghoa")]
        public XPCollection<Hanghoa> Hanghoas { get { return GetCollection<Hanghoa>(nameof(Hanghoas)); } }
    }

}
