//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("TenNCC")]
    public partial class Nhacungcap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenNCC;
        public string TenNCC
        {
            get { return fTenNCC; }
            set { SetPropertyValue<string>(nameof(TenNCC), ref fTenNCC, value); }
        }
        string fDiachiNCC;
        public string DiachiNCC
        {
            get { return fDiachiNCC; }
            set { SetPropertyValue<string>(nameof(DiachiNCC), ref fDiachiNCC, value); }
        }
        string fSDTNCC;
        public string SDTNCC
        {
            get { return fSDTNCC; }
            set { SetPropertyValue<string>(nameof(SDTNCC), ref fSDTNCC, value); }
        }
        [Association(@"PhieunhapReferencesNhacungcap")]
        public XPCollection<Phieunhap> Phieunhaps { get { return GetCollection<Phieunhap>(nameof(Phieunhaps)); } }
        [Association(@"PhieuchiReferencesNhacungcap")]
        public XPCollection<Phieuchi> Phieuchis { get { return GetCollection<Phieuchi>(nameof(Phieuchis)); } }
    }

}
