//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("HotenNV")]
    public partial class Nhanvien : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHotenNV;
        public string HotenNV
        {
            get { return fHotenNV; }
            set { SetPropertyValue<string>(nameof(HotenNV), ref fHotenNV, value); }
        }
        string fChucvuNV;
        public string ChucvuNV
        {
            get { return fChucvuNV; }
            set { SetPropertyValue<string>(nameof(ChucvuNV), ref fChucvuNV, value); }
        }
        string fSDTNV;
        public string SDTNV
        {
            get { return fSDTNV; }
            set { SetPropertyValue<string>(nameof(SDTNV), ref fSDTNV, value); }
        }
        string fLuongcoban;
        public string Luongcoban
        {
            get { return fLuongcoban; }
            set { SetPropertyValue<string>(nameof(Luongcoban), ref fLuongcoban, value); }
        }
        [Association(@"ChamcongReferencesNhanvien")]
        public XPCollection<Chamcong> Chamcongs { get { return GetCollection<Chamcong>(nameof(Chamcongs)); } }
        [Association(@"PhieunhapReferencesNhanvien")]
        public XPCollection<Phieunhap> Phieunhaps { get { return GetCollection<Phieunhap>(nameof(Phieunhaps)); } }
        [Association(@"PhieuchiReferencesNhanvien")]
        public XPCollection<Phieuchi> Phieuchis { get { return GetCollection<Phieuchi>(nameof(Phieuchis)); } }
        [Association(@"BangluongReferencesNhanvien"), Aggregated]
        public XPCollection<Bangluong> Bangluongs { get { return GetCollection<Bangluong>(nameof(Bangluongs)); } }
    }

}
