//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Doanvat.Module.Doanvat
{

    [DefaultProperty("Nhanvien_ID")]
    public partial class Phieuchi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvien_ID;
        [Association(@"PhieuchiReferencesNhanvien")]
        public Nhanvien Nhanvien_ID
        {
            get { return fNhanvien_ID; }
            set { SetPropertyValue<Nhanvien>(nameof(Nhanvien_ID), ref fNhanvien_ID, value); }
        }
        Nhacungcap fNhacungcap_ID;
        [Association(@"PhieuchiReferencesNhacungcap")]
        public Nhacungcap Nhacungcap_ID
        {
            get { return fNhacungcap_ID; }
            set { SetPropertyValue<Nhacungcap>(nameof(Nhacungcap_ID), ref fNhacungcap_ID, value); }
        }
        decimal fSotien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat","### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask","### ### ### ###")]
        public decimal Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<decimal>(nameof(Sotien), ref fSotien, value); }
        }
        DateTime fNgay;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask","dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat","{0:dd/MM/yyyy HH:mm}")
]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        string fLoaithuchi;
        public string Loaithuchi
        {
            get { return fLoaithuchi; }
            set { SetPropertyValue<string>(nameof(Loaithuchi), ref fLoaithuchi, value); }
        }
    }

}
